/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.controller;

import javafx.application.Application;
import javafx.stage.Stage;
import logic.model.Calendar;
import logic.model.User;
import logic.service.CalendarService;
import logic.service.UserService;

import javax.swing.*;

public class App extends Application {

    private Stage primaryStage;

    @Override
    public void start(Stage stage) throws Exception {
        this.primaryStage = primaryStage;
        this.primaryStage.setTitle("My first JavaFX app");

        this.appController = new AccountAppController(primaryStage);
        this.appController.initRootLayout();
    }
    
//    public static void main(String[] args)
//    {
//        User user = new User("u1", "aps");
//        System.out.println("Hello " + user.getUsername());
//
//        UserService service = new UserService();
//
//        service.addUser(user);
//
//        Calendar calendar = new Calendar("someName", user);
//        Calendar calendar2 = new Calendar("otherName", user);
//        calendar2.setDescription("desc");
//
//        CalendarService calendarService = new CalendarService();
//        calendarService.addCalendar(calendar);
//        calendarService.addCalendar(calendar2);
//
//        user.getCalendars().forEach(System.out::println);
//    }


}
