/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import app.controller.StartController;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {

    private Stage primaryStage;
    private StartController appController;

    @Override
    public void start(Stage stage) {
        this.primaryStage = stage;
        this.primaryStage.setTitle("Calendar");
        this.appController = new StartController(primaryStage);
        this.appController.initRootLayout();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
