/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import logic.model.User;

public class App {
    public static void main(String[] args)
    {
        User user = new User("u1", "aps");
        System.out.println("Hello "+user.getUsername());
    }
}
